#spring.application.name=journalApp
#
#
##localhost → MongoDB is on your computer
##27017    → MongoDB's default port
##journaldb → database name
##
##spring.mongodb.uri=mongodb://localhost:27017/journaldb
##mongodb+srv://USERNAME:PASSWORD@HOST/DATABASE?OPTIONS
#
#spring.mongodb.uri=mongodb+srv://ronacksingh41_db_user:na9gcMBa2HBX0zu1@cluster0.ie20pqb.mongodb.net/journaldb?appName=Cluster0
#spring.data.mongodb.auto-index-creation=true

#server.port=8087
##server.servlet.context-path=/App

#spring.profiles.active= prod
